version: '3.7'
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.16.3
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    container_name: kibana
    image: kibana:7.16.3
    ports:
      - '9999:5601'
  logstash:
    container_name: logstash
    image: logstash:7.16.3
    ports:
      - '5001:5000'
      - '9600:9600'
    volumes:
      - type: bind
        source: ./logstash_pipeline/
        target: /usr/share/logstash/pipeline
        read_only: true
